version: "2"

linters:
  default: standard

formatters:
  enable:
    - gofumpt
    - goimports
    - swaggo
  settings:
    gofumpt:
      extra-rules: true
    goimports:
      local-prefixes:
        - github.com/NathanNgo/Questbook/backend

output:
  formats:
    - name: text
      path: stdout
      settings:
        print-issued-lines: true
        print-linter-name: true
    - name: github-actions
      path: stdout