CREATE TABLE comments (
    id SERIAL PRIMARY KEY,
    session_id INTEGER NOT NULL REFERENCES sessions(id) ON DELETE CASCADE,
    text TEXT not NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);