/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/sessions": {
    /** Get all currently stored sessions */
    get: {
      responses: {
        /** OK */
        200: {
          schema: definitions["internal_api_server.GetAllSessionsResponseObject"][];
        };
        /** Internal Error */
        500: {
          schema: string;
        };
      };
    };
    /** Create a new session with the provided session name */
    post: {
      parameters: {
        body: {
          /** Session details */
          request: definitions["internal_api_server.CreateSessionRequestPayload"];
        };
      };
      responses: {
        /** Created */
        201: {
          schema: definitions["internal_api_server.CreateSessionResponse"];
        };
        /** Invalid JSON payload */
        400: {
          schema: string;
        };
        /** Database Error */
        500: {
          schema: string;
        };
      };
    };
  };
  "/sessions/{id}": {
    /** Finds and returns a session object using an ID */
    get: {
      parameters: {
        path: {
          /** Session ID */
          id: string;
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["internal_api_server.GetSessionResponse"];
        };
        /** ID is required */
        400: {
          schema: string;
        };
        /** Internal Error */
        500: {
          schema: string;
        };
      };
    };
    /** Deletes a session that matches a given ID */
    delete: {
      parameters: {
        path: {
          /** Session ID */
          id: string;
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["internal_api_server.DeleteSessionResponse"];
        };
        /** ID is required */
        400: {
          schema: string;
        };
        /** Internal Error */
        500: {
          schema: string;
        };
      };
    };
  };
}

export interface definitions {
  "internal_api_server.CreateSessionRequestPayload": {
    sessionName?: string;
  };
  "internal_api_server.CreateSessionResponse": {
    id?: string;
    sessionName?: string;
  };
  "internal_api_server.DeleteSessionResponse": {
    id?: string;
    sessionName?: string;
  };
  "internal_api_server.GetAllSessionsResponseObject": {
    id?: string;
    sessionName?: string;
  };
  "internal_api_server.GetSessionResponse": {
    id?: string;
  };
}

export interface operations {}

export interface external {}
