definitions:
  internal_api_server.CreateSessionRequestPayload:
    properties:
      sessionName:
        type: string
    type: object
  internal_api_server.CreateSessionResponse:
    properties:
      id:
        type: string
      sessionName:
        type: string
    type: object
  internal_api_server.DeleteSessionResponse:
    properties:
      id:
        type: string
      sessionName:
        type: string
    type: object
  internal_api_server.GetAllSessionsResponseObject:
    properties:
      id:
        type: string
      sessionName:
        type: string
    type: object
  internal_api_server.GetSessionResponse:
    properties:
      id:
        type: string
    type: object
info:
  contact: {}
  description: API server for Questbook
  title: Questbook API Server
  version: "1.0"
paths:
  /sessions:
    get:
      description: Get all currently stored sessions
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/internal_api_server.GetAllSessionsResponseObject'
            type: array
        "500":
          description: Internal Error
          schema:
            type: string
      summary: Gets all sessions
      tags:
      - sessions
    post:
      consumes:
      - application/json
      description: Create a new session with the provided session name
      parameters:
      - description: Session details
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/internal_api_server.CreateSessionRequestPayload'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/internal_api_server.CreateSessionResponse'
        "400":
          description: Invalid JSON payload
          schema:
            type: string
        "500":
          description: Database Error
          schema:
            type: string
      summary: Create a new session
      tags:
      - sessions
  /sessions/{id}:
    delete:
      description: Deletes a session that matches a given ID
      parameters:
      - description: Session ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/internal_api_server.DeleteSessionResponse'
        "400":
          description: ID is required
          schema:
            type: string
        "500":
          description: Internal Error
          schema:
            type: string
      summary: Deletes a session by session ID
      tags:
      - sessions
    get:
      description: Finds and returns a session object using an ID
      parameters:
      - description: Session ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/internal_api_server.GetSessionResponse'
        "400":
          description: ID is required
          schema:
            type: string
        "500":
          description: Internal Error
          schema:
            type: string
      summary: Gets a session by session ID
      tags:
      - sessions
swagger: "2.0"
