name: Backend CI

on:
  push:
    branches: [ "main" ]
    paths:
      - 'backend/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'backend/**'

jobs:
  lint-and-format:
    name: Lint and Format Go
    runs-on: ubuntu-latest
    permissions:
        contents: read
    
    defaults:
      run:
        working-directory: ./backend

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25.4'
          cache-dependency-path: backend/go.sum

      - name: Run golangci-lint (Linting and Formatting)
        uses: golangci/golangci-lint-action@v9
        with:
          version: v2.12.0
          working-directory: backend