name: Backend CI

on:
  push:
    branches: [ "main" ]
    paths:
      - 'backend/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'backend/**'

permissions:
    contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint-and-format-go:
    name: Lint and Format Go
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./backend

    steps:
      - name: Check out code
        uses: actions/checkout@v6

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: '1.25.4'
          cache-dependency-path: backend/go.sum

      - name: Run golangci-lint (Linting and Formatting)
        uses: golangci/golangci-lint-action@v9
        with:
          version: v2.12.0
          working-directory: backend

  lint-and-format-sql:
    name: Lint and Format SQL
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./backend

    steps:
      - name: Check out code
        uses: actions/checkout@v6
    
      - name: Run ls-lint
        uses: ls-lint/action@v2
        with:
          workdir: backend
          config: backend/.ls-lint.yml

      - uses: actions/setup-python@v6
        with:
          python-version: '3.14'

      - name: Install SQLFluff
        run: pip install sqlfluff==4.1.0

      - name: Run SQLFluff
        run: sqlfluff lint ./migrations --config .sqlfluff --format github-annotation-native

  database-migration-check:
    name: Database Migration Check
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./backend

    services:
      postgres:
        image: postgres:18.3-alpine
        env:
          POSTGRES_USER: admin
          POSTGRES_PASSWORD: password
          POSTGRES_DB: questbook
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U admin -d testdb"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Check out code
        uses: actions/checkout@v6

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: '1.25.4'
          cache-dependency-path: backend/go.sum

      - name: Run Migrations "Up"
        run: make migrate

      - name: Run Migrations "Down"
        run: make migrate-down